version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: ../docker/frontend.Dockerfile

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: ../docker/backend.Dockerfile

  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: ../docker/nginx.Dockerfile
    ports:
      - 8080:80
