apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          imagePullPolicy: Always
          image: gcr.io/k8s-free/backend:0.1.2
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      name: http
---
kind: Service
apiVersion: v1
metadata:
  name: postgresql
spec:
  type: ExternalName
  externalName: postgresql.postgresql.svc.cluster.local
  ports:
    - port: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: { { REPLACE } }
  POSTGRES_USER: { { REPLACE } }
  POSTGRES_PASSWORD: { { REPLACE } }
  POSTGRES_HOST: { { REPLACE } }
  POSTGRES_PORT: { { REPLACE } }
